name: pokemon_bloc_flutter
description: "A Flutter app demonstrating BLoC pattern with Pokemon API integration"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  http: ^1.1.0
  get_it: ^7.6.4
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true